### ISSUE TITLE
the method getStepIndexFromDate in Interval class problem

### ISSUE THREAD

**Issue by yuzhe10** [Ifnot/statistics#3]
I got a wrong step index while the current step is yearly or monthly, such as:
Carbon date = '2017-06-23 17:01:04';
$this->step = 'monthly';
then the result of step index is "2017-05",  it's not correct, right?
The following is my correction, pls let me know if something wrong.

`/**
     * Converting a date to his step index according to the step precision of the interval
     *
     * @param Carbon $date
     * @return string
     */
    public function getStepIndexFromDate(Carbon $date)
    {
        switch ($this->step) {
            case "yearly":
                $date->month = 1;
            case "monthly":
                $date->day = 1;
            case "daily":
                $date->hour = 0;
            case "hourly":
                $date->minute = 0;
            default:
                $date->second = 0;
                break;
        }

        return $date->format($this->getStepFormat());
    }`

**Comment by IfnotFr** [comment]
Hi and thanks for your feedback !

It makes sense. I will check this fix on my projects.

Maybe if i have time i will write some tests.

**Comment by IfnotFr** [comment]
I was able to find the issue.

This is now fixed with 8339229aa03f5fe5d76573762dd38915de32f9f5
